### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ardacebi** [bgrgndzz/bloom#7]
- [ ] Add the ability to save threads (bookmark for later)
- [ ] Add the ability to reply to specific posts (comments)
- [ ] Replace bookmark icon on the first tab (bottom bar) with home and create a search interface
- [ ] Integrate settings into user page for extra space (remove settings tab)
- [ ] Change bottom bar order: Home ---> Search ---> Profile
- [ ] Add the ability to search on home
- [ ] Add age, district, and usernames to profiles
- [ ] Create separate school pages that host all users in a list & posts in a list
- [ ] Add date & time to posts
